apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secret
data:
  password: {{ include "pgadmin.password" . | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: redpanda-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ htpasswd "admin" (include "redpanda.password" .) | b64enc }}
  password: {{ include "redpanda.password" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-users-secret
data:
  redpanda: {{ include "redpandakafkauser.password" . | b64enc }}
  notification: {{ include "notificationkafkauser.password" . | b64enc }}
  {{- range .Values.agentList.authorities }}
  "{{ . }}_authprovider": {{ randAlphaNum 16 | nospace | b64enc }}
  "{{ . }}_usersroles": {{ randAlphaNum 16 | nospace | b64enc }}
  "{{ . }}_onboarding": {{ randAlphaNum 16 | nospace | b64enc }}
  "{{ . }}_tier2gw": {{ randAlphaNum 16 | nospace | b64enc }}
  {{- end }}
  {{- range .Values.agentList.providers }}
  "{{ . }}_authprovider": {{ randAlphaNum 16 | nospace | b64enc }}
  "{{ . }}_usersroles": {{ randAlphaNum 16 | nospace | b64enc }}
  "{{ . }}_contract": {{ randAlphaNum 16 | nospace | b64enc }}
  "{{ . }}_infrabe": {{ randAlphaNum 16 | nospace | b64enc }}
  "{{ . }}_tier2gw": {{ randAlphaNum 16 | nospace | b64enc }}
  {{- end }}
  {{- range .Values.agentList.consumers }}
  "{{ . }}_authprovider": {{ randAlphaNum 16 | nospace | b64enc }}
  "{{ . }}_usersroles": {{ randAlphaNum 16 | nospace | b64enc }}
  "{{ . }}_contract": {{ randAlphaNum 16 | nospace | b64enc }}
  "{{ . }}_contract_consumption": {{ randAlphaNum 16 | nospace | b64enc }}
  "{{ . }}_tier2gw": {{ randAlphaNum 16 | nospace | b64enc }}
  {{- end }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
data:
  redis: {{ include "redis.password" . | b64enc }}
  commander: {{ include "rediscommander.password" . | b64enc }}
type: Opaque
{{- if .Values.mailpit.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mailpit-secrets
data:
  ui: {{ include "mailpitui.password" . | b64enc }}
  ui.htpasswd: {{ htpasswd "admin" (include "mailpitui.password" .) | b64enc }}
  smtp: {{ "smtppass" | b64enc }}
  smtp.htpasswd: {{ htpasswd "smtp" "smtppass" | b64enc }}
type: Opaque
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
data:
  {{- range .Values.agentList.authorities }}
  {{ . }}: {{ randAlphaNum 16 | nospace | b64enc }}
  {{- end }}
  {{- range .Values.agentList.providers }}
  {{ . }}: {{ randAlphaNum 16 | nospace | b64enc }}
  {{- end }}
  {{- range .Values.agentList.consumers }}
  {{ . }}: {{ randAlphaNum 16 | nospace | b64enc }}
  {{- end }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
data:
  gitops_test: {{ randAlphaNum 16 | nospace | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ejbca-secret
data:
  keystorepass: {{ randAlphaNum 16 | nospace | b64enc }}
type: Opaque